version: '3.7'
services:
  server:
    image: registry.query.consul:5000/platform/redash:latest
    command: server
    depends_on:
      - postgres
      - redis
    ports:
      - "5000:5000"
    environment:
      PYTHONUNBUFFERED: 0
      REDASH_LOG_LEVEL: "INFO"
      REDASH_REDIS_URL: "redis://redis:6379/0"
      REDASH_DATABASE_URL: YOUR_DB_URI
      REDASH_COOKIE_SECRET: YOUR_COOKIE_SECRET
      REDASH_WEB_WORKERS: 4
  worker:
    image: registry.query.consul:5000/platform/redash:latest
    command: scheduler
    environment:
      PYTHONUNBUFFERED: 0
      REDASH_LOG_LEVEL: "INFO"
      REDASH_REDIS_URL: "redis://redis:6379/0"
      REDASH_DATABASE_URL: YOUR_DB_URI
      QUEUES: "queries,scheduled_queries,celery"
      WORKERS_COUNT: 2
      REDASH_COOKIE_SECRET: YOUR_COOKIE_SECRET
  redis:
    image: registry.query.consul:5000/redis:5.0-alpine 
postgres:
    image: postgres:9.5
    ports:
    - "5432:5432"
